<?php
require_once '../models/Connect.php';
require_once '../models/AdminModel.php';
require_once '../models/Close.php';
session_start();

if (!isset($_SESSION['user_role']) || $_SESSION['user_role'] !== 'admin') {
    header('Location: LoginPageController.php');
    die();
}

$conn = Connect();
$borrows  = getBorrowsPerMonth($conn);
$fines    = getFinesPerMonth($conn);
$branches = getMostActiveBranches($conn);
$genres   = getMostBorrowedGenres($conn);
$growth   = getMemberGrowthPerMonth($conn);
close($conn);

// Output as downloadable HTML
header('Content-Type: text/html');
header('Content-Disposition: attachment; filename="library_report_' . date('Y-m-d') . '.html"');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Library Report — <?= date('Y-m-d') ?></title>
    <style>
        body { font-family: Arial, sans-serif; padding: 30px; color: #333; }
        h1 { color: #4f46e5; margin-bottom: 6px; }
        h2 { margin-top: 30px; margin-bottom: 10px; color: #555; border-bottom: 2px solid #4f46e5; padding-bottom: 6px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #4f46e5; color: #fff; padding: 10px; text-align: left; }
        td { padding: 9px 10px; border-bottom: 1px solid #eee; }
        .footer { margin-top: 40px; font-size: 12px; color: #999; }
    </style>
</head>
<body>
    <h1>📚 Library Management System</h1>
    <p>Report generated on: <strong><?= date('F j, Y h:i A') ?></strong></p>

    <h2>Borrows Per Month</h2>
    <table>
        <thead><tr><th>Month</th><th>Total Borrows</th></tr></thead>
        <tbody>
        <?php foreach ($borrows as $row): ?>
            <tr><td><?= $row['month'] ?></td><td><?= $row['total'] ?></td></tr>
        <?php endforeach; ?>
        <?php if (empty($borrows)): ?>
            <tr><td colspan="2">No data available</td></tr>
        <?php endif; ?>
        </tbody>
    </table>

    <h2>Fines Collected Per Month</h2>
    <table>
        <thead><tr><th>Month</th><th>Total Fines (৳)</th></tr></thead>
        <tbody>
        <?php foreach ($fines as $row): ?>
            <tr><td><?= $row['month'] ?></td><td>৳<?= number_format($row['total'], 2) ?></td></tr>
        <?php endforeach; ?>
        <?php if (empty($fines)): ?>
            <tr><td colspan="2">No data available</td></tr>
        <?php endif; ?>
        </tbody>
    </table>

    <h2>Most Active Branches</h2>
    <table>
        <thead><tr><th>Branch</th><th>Total Borrows</th></tr></thead>
        <tbody>
        <?php foreach ($branches as $row): ?>
            <tr><td><?= htmlspecialchars($row['branch_name']) ?></td><td><?= $row['total_borrows'] ?></td></tr>
        <?php endforeach; ?>
        <?php if (empty($branches)): ?>
            <tr><td colspan="2">No data available</td></tr>
        <?php endif; ?>
        </tbody>
    </table>

    <h2>Most Borrowed Genres</h2>
    <table>
        <thead><tr><th>Genre</th><th>Total Borrows</th></tr></thead>
        <tbody>
        <?php foreach ($genres as $row): ?>
            <tr><td><?= htmlspecialchars($row['genre_name']) ?></td><td><?= $row['total_borrows'] ?></td></tr>
        <?php endforeach; ?>
        <?php if (empty($genres)): ?>
            <tr><td colspan="2">No data available</td></tr>
        <?php endif; ?>
        </tbody>
    </table>

    <h2>Member Growth Per Month</h2>
    <table>
        <thead><tr><th>Month</th><th>New Members</th></tr></thead>
        <tbody>
        <?php foreach ($growth as $row): ?>
            <tr><td><?= $row['month'] ?></td><td><?= $row['total'] ?></td></tr>
        <?php endforeach; ?>
        <?php if (empty($growth)): ?>
            <tr><td colspan="2">No data available</td></tr>
        <?php endif; ?>
        </tbody>
    </table>

    <div class="footer">Generated by Library Management System Admin Panel</div>
</body>
</html>
<?php die(); ?>
